### ISSUE TITLE
XMLSyntaxError while trying to connect

### ISSUE THREAD

**Issue by floriansiepe** [vlaci/openconnect-sso#12]
The latest version (0.4) throws an XML error while authentificating.
Connecting with the official Anyconnect client works.

```
openconnect-sso <server>

Traceback (most recent call last):
  File "/usr/bin/openconnect-sso", line 11, in <module>
    load_entry_point('openconnect-sso==0.4.0', 'console_scripts', 'openconnect-sso')()
  File "/usr/lib/python3.8/site-packages/openconnect_sso/cli.py", line 150, in main
    return app.run(args)
  File "/usr/lib/python3.8/site-packages/openconnect_sso/app.py", line 28, in run
    return asyncio.get_event_loop().run_until_complete(_run(args))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 612, in run_until_complete
    return future.result()
  File "/usr/lib/python3.8/site-packages/openconnect_sso/app.py", line 98, in _run
    auth_response = await authenticate_to(selected_profile, credentials, display_mode)
  File "/usr/lib/python3.8/site-packages/openconnect_sso/authenticator.py", line 21, in authenticate
    response = self._start_authentication()
  File "/usr/lib/python3.8/site-packages/openconnect_sso/authenticator.py", line 65, in _start_authentication
    return parse_response(response)
  File "/usr/lib/python3.8/site-packages/openconnect_sso/authenticator.py", line 133, in parse_response
    xml = objectify.fromstring(resp.content)
  File "src/lxml/objectify.pyx", line 1808, in lxml.objectify.fromstring
  File "src/lxml/etree.pyx", line 3235, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1876, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1764, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1127, in lxml.etree._BaseParser._parseDoc
  File "src/lxml/parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 711, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 640, in lxml.etree._raiseParseError
  File "<string>", line 6
lxml.etree.XMLSyntaxError: Opening and ending tag mismatch: br line 4 and body, line 6, column 9
```

**Comment by agncr** [comment]
@Flo9818  Were you able to solve your problem? I have a similar error message...

**Comment by vlaci** [comment]
Could you start with `-l debug` argument? The line starting with `[debug ] Auth init response received` should continue with an XML like the following
```<?xml version="1.0" encoding="UTF-8"?>
<config-auth client="vpn" type="auth-request" aggregate-auth-version="2">
<opaque is-for="sg">
<tunnel-group>Q-Employee</tunnel-group>
<auth-method>single-sign-on-v2</auth-method>
<group-alias>Employee (Global)</group-alias>
<config-hash>1567100134259</config-hash>
</opaque>
<auth id="main">
<title>Login</title>
<message>Please complete the authentication process in the AnyConnect Login window.</message>
<banner></banner>
<sso-v2-login>...</sso-v2-login>
<sso-v2-login-final>...</sso-v2-login-final>
<sso-v2-logout>...</sso-v2-logout>
<sso-v2-logout-final>...</sso-v2-logout-final>
<sso-v2-token-cookie-name>acSamlv2Token</sso-v2-token-cookie-name>
<sso-v2-error-cookie-name>acSamlv2Error</sso-v2-error-cookie-name>
<form>
<input type="sso" name="sso-token"></input>
...
</select>
</form>
</auth>
</config-auth>```

**Comment by agncr** [comment]
I'm getting the following:
```
[debug    ] Auth init response received    [openconnect_sso.authenticator] content=b'this is just a place holder file for sslvpn handler.\r\nthe sslvpn handler should be triggered and process the http request.\r\n'
Traceback (most recent call last):
  File "/home/abdullah/.local/bin/openconnect-sso", line 8, in <module>
    sys.exit(main())
  File "/home/abdullah/.local/pipx/venvs/openconnect-sso/lib/python3.8/site-packages/openconnect_sso/cli.py", line 150, in main
    return app.run(args)
  File "/home/abdullah/.local/pipx/venvs/openconnect-sso/lib/python3.8/site-packages/openconnect_sso/app.py", line 28, in run
    return asyncio.get_event_loop().run_until_complete(_run(args))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/abdullah/.local/pipx/venvs/openconnect-sso/lib/python3.8/site-packages/openconnect_sso/app.py", line 98, in _run
    auth_response = await authenticate_to(selected_profile, credentials, display_mode)
  File "/home/abdullah/.local/pipx/venvs/openconnect-sso/lib/python3.8/site-packages/openconnect_sso/authenticator.py", line 21, in authenticate
    response = self._start_authentication()
  File "/home/abdullah/.local/pipx/venvs/openconnect-sso/lib/python3.8/site-packages/openconnect_sso/authenticator.py", line 65, in _start_authentication
    return parse_response(response)
  File "/home/abdullah/.local/pipx/venvs/openconnect-sso/lib/python3.8/site-packages/openconnect_sso/authenticator.py", line 133, in parse_response
    xml = objectify.fromstring(resp.content)
  File "src/lxml/objectify.pyx", line 1808, in lxml.objectify.fromstring
  File "src/lxml/etree.pyx", line 3235, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1876, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1764, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1127, in lxml.etree._BaseParser._parseDoc
  File "src/lxml/parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 711, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 640, in lxml.etree._raiseParseError
  File "<string>", line 1
lxml.etree.XMLSyntaxError: Start tag expected, '<' not found, line 1, column 1
~ ❯                                                                              
```

**Comment by vlaci** [comment]
Unfortunately `openconnect-sso` only works with Cisco VPNs at the moment.

**Comment by agncr** [comment]
Ah, okay. Should have known that, it's written on your Readme :upside_down_face:

**Comment by Flo9818** [comment]
> @Flo9818 Were you able to solve your problem? I have a similar error message...

Sorry for the late reply. It was my stupid mistake. I was using the wrong URL

**Comment by fchris82** [comment]
@vlaci I would like to connect to a Cisco VPN. Anyconnect works well. But if I try to use `openconnect-sso` I found different errors.

#### Version 1

```shell
$ openconnect-sso --server https://vpn.something.com/Azure --user username@something.com -l DEBUG
Using selector: EpollSelector
[info     ] Authenticating to VPN endpoint [openconnect_sso.app] address=https://vpn.something.com/Azure name=UNNAMED
Starting new HTTPS connection (1): vpn.something.com:443
https://vpn.something.com:443 "GET /Azure HTTP/1.1" 302 0
Resetting dropped connection: vpn.something.com
https://vpn.something.com:443 "GET /+CSCOE+/message.html?mc=2 HTTP/1.1" 200 None
[debug    ] Auth target url                [openconnect_sso.authenticator] url=https://vpn.something.com/+CSCOE+/message.html
Starting new HTTPS connection (1): vpn.something.com:443
https://vpn.something.com:443 "POST /+CSCOE+/message.html HTTP/1.1" 200 None
[debug    ] Auth init response received    [openconnect_sso.authenticator] content=b'\n<html>\n<body>\n<br>\n\n<center><b></b></center>\n</body>\n</html>\n\n\n'
Traceback (most recent call last):
  File "/home/chris/.local/bin/openconnect-sso", line 8, in <module>
    sys.exit(main())
  File "/home/chris/.local/pipx/venvs/openconnect-sso/lib/python3.6/site-packages/openconnect_sso/cli.py", line 150, in main
    return app.run(args)
  File "/home/chris/.local/pipx/venvs/openconnect-sso/lib/python3.6/site-packages/openconnect_sso/app.py", line 28, in run
    return asyncio.get_event_loop().run_until_complete(_run(args))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/home/chris/.local/pipx/venvs/openconnect-sso/lib/python3.6/site-packages/openconnect_sso/app.py", line 98, in _run
    auth_response = await authenticate_to(selected_profile, credentials, display_mode)
  File "/home/chris/.local/pipx/venvs/openconnect-sso/lib/python3.6/site-packages/openconnect_sso/authenticator.py", line 21, in authenticate
    response = self._start_authentication()
  File "/home/chris/.local/pipx/venvs/openconnect-sso/lib/python3.6/site-packages/openconnect_sso/authenticator.py", line 65, in _start_authentication
    return parse_response(response)
  File "/home/chris/.local/pipx/venvs/openconnect-sso/lib/python3.6/site-packages/openconnect_sso/authenticator.py", line 133, in parse_response
    xml = objectify.fromstring(resp.content)
  File "src/lxml/objectify.pyx", line 1808, in lxml.objectify.fromstring
  File "src/lxml/etree.pyx", line 3235, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1876, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1764, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1127, in lxml.etree._BaseParser._parseDoc
  File "src/lxml/parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 711, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 640, in lxml.etree._raiseParseError
  File "<string>", line 7
lxml.etree.XMLSyntaxError: Opening and ending tag mismatch: br line 4 and body, line 7, column 9
```

#### Version 2

```shell
$ openconnect-sso --server https://vpn.something.com --usergroup Azure --user username@something.com -l DEBUG
Using selector: EpollSelector
[info     ] Authenticating to VPN endpoint [openconnect_sso.app] address=https://vpn.something.com name=UNNAMED
Starting new HTTPS connection (1): vpn.something.com:443
https://vpn.something.com:443 "GET /Azure HTTP/1.1" 302 0
Resetting dropped connection: vpn.something.com
https://vpn.something.com:443 "GET /+CSCOE+/message.html?mc=2 HTTP/1.1" 200 None
[debug    ] Auth target url                [openconnect_sso.authenticator] url=https://vpn.something.com/Azure
Starting new HTTPS connection (1): vpn.something.com:443
https://vpn.something.com:443 "POST /Azure HTTP/1.1" 200 None
[debug    ] Auth init response received    [openconnect_sso.authenticator] content=b'<?xml version="1.0" encoding="UTF-8"?>\n<auth id="main">\n<error id="91" param1="" param2="">Invalid host entry. Please re-enter.</error>\n</auth>\n\n\n\n\n'
[error    ] Could not start authentication. Invalid response type in current state [openconnect_sso.authenticator] response=None
Traceback (most recent call last):
  File "/home/chris/.local/bin/openconnect-sso", line 8, in <module>
    sys.exit(main())
  File "/home/chris/.local/pipx/venvs/openconnect-sso/lib/python3.6/site-packages/openconnect_sso/cli.py", line 150, in main
    return app.run(args)
  File "/home/chris/.local/pipx/venvs/openconnect-sso/lib/python3.6/site-packages/openconnect_sso/app.py", line 28, in run
    return asyncio.get_event_loop().run_until_complete(_run(args))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/home/chris/.local/pipx/venvs/openconnect-sso/lib/python3.6/site-packages/openconnect_sso/app.py", line 98, in _run
    auth_response = await authenticate_to(selected_profile, credentials, display_mode)
  File "/home/chris/.local/pipx/venvs/openconnect-sso/lib/python3.6/site-packages/openconnect_sso/authenticator.py", line 27, in authenticate
    raise AuthenticationError(response)
openconnect_sso.authenticator.AuthenticationError: None
```

Once the program asked me for a password, after this: `openconnect-sso --server vpn.something.com --usergroup Azure --user username@something.com -l DEBUG` But I haven't been able to reproduce it again since then.

Do you have any idea where would be the problem?

**Comment by vlaci** [comment]
I have no idea what was going on there. The password is saved to your login keyring and it is being reused. You may remove the config file located under `~/.config/openconnect-sso/config.toml` to reset the stored state. Also if you have anyconnect installed on the default location you can use its stored profiles by skipping the endpoint related command line arguments or by passing the `--profile-selector` argument.

**Comment by vlaci** [comment]
After some googling I have found a possible culprit. Your VPN may need a valid authgroup entry (in openconnect terminology). It is the name you select in AnyConnect UI in the `Connect to` dropdown.
It is defaulted to `UNNAMED` when not using an anyconnect profile but command line arguments. You can fortunately override it in the config file. Just change the contents of ~/.config/openconnect-sso/config.toml` to contain the following: 
```toml
[default_profile]
name = "your desired authgroup"
```
If the meantime I'll rework the command line interface to allow specifying this option too.

Using the existing AnyConnect profile by passing `--profile-selector` should also fix your issue.

**Comment by fchris82** [comment]
Current config file:
```toml
[default_profile]
address = "vpn.something.com"
user_group = "Azure"
name = "Azure"

[credentials]
username = "username@something.com"

[auto_fill_rules]
[[auto_fill_rules."https://*"]]
selector = "div[id=passwordError]"
action = "stop"

[[auto_fill_rules."https://*"]]
selector = "input[type=email]"
fill = "username"

[[auto_fill_rules."https://*"]]
selector = "input[type=password]"
fill = "password"

[[auto_fill_rules."https://*"]]
selector = "input[type=submit]"
action = "click"
```

Commands:

```shell
$ openconnect-sso --profile-selector -l DEBUG
usage: openconnect-sso [-h] [-p PROFILE_PATH] [-P] [-s SERVER] [-g USERGROUP]
                       [--authenticate [OUTPUT-FORMAT]]
                       [--browser-display-mode [DISPLAY-MODE]] [-V]
                       [-l {ERROR,WARNING,INFO,DEBUG}] [-u USER]
                       ...
openconnect-sso: error: No AnyConnect profile can be found. --profile argument is required.

$ openconnect-sso --profile Azure -l DEBUG         
Using selector: EpollSelector
[info     ] Authenticating to VPN endpoint [openconnect_sso.app] address=vpn.something.com name=Azure
Starting new HTTPS connection (1): vpn.something.com:443
https://vpn.something.com:443 "GET /Azure HTTP/1.1" 302 0
Resetting dropped connection: vpn.something.com
https://vpn.something.com:443 "GET /+CSCOE+/message.html?mc=2 HTTP/1.1" 200 None
[debug    ] Auth target url                [openconnect_sso.authenticator] url=https://vpn.something.com/Azure
Starting new HTTPS connection (1): vpn.something.com:443
https://vpn.something.com:443 "POST /Azure HTTP/1.1" 200 None
[debug    ] Auth init response received    [openconnect_sso.authenticator] content=b'<?xml version="1.0" encoding="UTF-8"?>\n<auth id="main">\n<error id="91" param1="" param2="">Invalid host entry. Please re-enter.</error>\n</auth>\n\n\n\n\n'
[error    ] Could not start authentication. Invalid response type in current state [openconnect_sso.authenticator] response=None
Traceback (most recent call last):
  File "/home/chris/.local/bin/openconnect-sso", line 8, in <module>
    sys.exit(main())
  File "/home/chris/.local/pipx/venvs/openconnect-sso/lib/python3.6/site-packages/openconnect_sso/cli.py", line 150, in main
    return app.run(args)
  File "/home/chris/.local/pipx/venvs/openconnect-sso/lib/python3.6/site-packages/openconnect_sso/app.py", line 28, in run
    return asyncio.get_event_loop().run_until_complete(_run(args))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/home/chris/.local/pipx/venvs/openconnect-sso/lib/python3.6/site-packages/openconnect_sso/app.py", line 98, in _run
    auth_response = await authenticate_to(selected_profile, credentials, display_mode)
  File "/home/chris/.local/pipx/venvs/openconnect-sso/lib/python3.6/site-packages/openconnect_sso/authenticator.py", line 27, in authenticate
    raise AuthenticationError(response)
openconnect_sso.authenticator.AuthenticationError: None

**Comment by vlaci** [comment]
You have mentioned that you can connect via Anyconnect? Is there a stored profile for it or do you need to enter connection details everytime you are using that?

**Comment by fchris82** [comment]
I have to type the URL every time when I want to connect.

**Comment by vlaci** [comment]
My last idea is that you could try to set name to be empty in the config file:
```
name = ""
```

**Comment by fchris82** [comment]
Same. Maybe local permission problem? If I want to use openconnect, I have to use it with `sudo`. So maybe I should install openconnect-sso as root, and try with `sudo`? Or it is impossible that this is the problem?

**Comment by vlaci** [comment]
Not being root is not a problem. The authentication itself is just a bunch of https request-responses. `openconnect` is started via `sudo` after the authentication itself succeeds.

I'd need traffic dumps of the working Anyconnect authentication flow in order to further diagnose the issue. You don't need to enter your credentials so they would not be captured.
Such a dump can be created by using e.g [mitmproxy](https://mitmproxy.org/). It is not an easy task because you'd need to terminate the TLS connection in order to capture clear text traffic.

**Comment by fchris82** [comment]
[anyconnect.log](https://github.com/vlaci/openconnect-sso/files/4486167/anyconnect.log)

Here is the "log". First 3 block is the "start" step, second 3 block is the "login". Is it usable?

**Comment by fchris82** [comment]
:information_source: I had to create a `Profile.xml` file to use proxy. If I set `<UserGroup>Azure</UserGroup>` I got an error message in Anyconnect to change gateway. After deleting this row it worked.

**Comment by vlaci** [comment]
Thanks!
I have an idea how to fix your issue.

In the meantime could you save the attached profile.xml (note the empty usergroup):

```xml
<?xml version="1.0" encoding="UTF-8"?>
<AnyConnectProfile xmlns="http://schemas.xmlsoap.org/encoding/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <ServerList>
    <HostEntry>
      <HostName>Azure</HostName>
      <HostAddress>vpn.something.com</HostAddress>
      <UserGroup></UserGroup>
    </HostEntry>
  </ServerList>
</AnyConnectProfile>
```
Then run:
`openconnect-sso  --profile /path/to/above/profile.xml --use-profile-selector`
It should produce a very similar auth request to the one you have shown. The only difference is an additional trailing slash in the vpn url in the `<group-access>` node.

If we can come up with a profile.xml that works for you, I can adjust the code to make it work without that.

**Comment by fchris82** [comment]
I got this error:
```xml
[debug    ] Auth init response received    [openconnect_sso.authenticator] content=b'
<?xml version="1.0" encoding="UTF-8"?>
<config-auth client="vpn" type="auth-request" aggregate-auth-version="2">
  <opaque is-for="sg">
    <tunnel-group>Azure</tunnel-group>
    <auth-method>single-sign-on-v2</auth-method>
    <group-alias>Azure</group-alias>
    <config-hash>1583754467210</config-hash>
  </opaque>
  <auth id="main">
    <message>Please complete the authentication process in the AnyConnect Login window.</message>
    <sso-v2-login>https://vpn.something.com/+CSCOE+/saml/sp/login?tgname=Azure&#x26;acsamlcap=v2</sso-v2-login>
    <sso-v2-login-final>https://vpn.something.com/+CSCOE+/saml_ac_login.html</sso-v2-login-final>
    <sso-v2-logout>https://vpn.something.com/+CSCOE+/saml/sp/logout</sso-v2-logout>
    <sso-v2-logout-final>https://vpn.something.com/+CSCOE+/saml_ac_login.html</sso-v2-logout-final>
    <sso-v2-token-cookie-name>acSamlv2Token</sso-v2-token-cookie-name>
    <sso-v2-error-cookie-name>acSamlv2Error</sso-v2-error-cookie-name>
    <form>
      <input type="sso" name="sso-token"></input>
      <select name="group_list" label="GROUP:">
        <option selected="true">Azure</option>
        <option>OTHER_GRP</option>
        <option>VPN</option>
      </select>
    </form>
  </auth>
</config-auth>
'
[error    ] Required attributes not found in response ("no such child: title", does this endpoint do SSO?), exiting [openconnect_sso.app] 
```

I formatted the xml to be readable.

**Comment by vlaci** [comment]
Oh, it almost works now. I just expect an element that your endpoint does not provide. I can easily fix that.

**Comment by vlaci** [comment]
I have uploaded a new pre-release version `v0.5.0a1`. Hopefully it'll fix the `"no such child: title"` error. It also introduces the `--authgroup` option from openconnect so that it is no longer needed to have an AnyConnect profile to provide its value.

**Comment by fchris82** [comment]
:fireworks: Perfect, it works :) Thank you :)

**Comment by fchris82** [comment]
@vlaci OFF: As I can see the password was saved. I have to change my password regularly. How can I change it later?

**Comment by vlaci** [comment]
The password is stored on the logon keyring. You should see the credential there and you can update via your tool of choice, e. g. `kdewallet`, `seahorse` or `secret-tool` if you prefer the command line.

I am thinking on extending the credential management of `openconnect-sso` to make this easier in the future.

**Comment by jjeziorny** [comment]
> I have uploaded a new pre-release version `v0.5.0a1`. Hopefully it'll fix the `"no such child: title"` error. It also introduces the `--authgroup` option from openconnect so that it is no longer needed to have an AnyConnect profile to provide its value.

All, having similar issue here. How can I download the V0.5.0a1 version to see if it clears my issue?

**Comment by vlaci** [comment]
It's on the releases page
https://github.com/vlaci/openconnect-sso/releases/tag/v0.5.0a1

**Comment by jjeziorny** [comment]
no luck for me I'm afraid, still getting the Invalid response error even with 0.5.0a1

`$ openconnect-sso -l debug
Using selector: EpollSelector
[info     ] Authenticating to VPN endpoint [openconnect_sso.app] address=vpn.company.com name=CI-VPN
Starting new HTTPS connection (1): vpn.company.com:443
https://vpn.company.com:443 "GET / HTTP/1.1" 200 None
[debug    ] Auth target url                [openconnect_sso.authenticator] url=https://vpn.company.com/
[debug    ] Sending auth init request      [openconnect_sso.authenticator] content=b'<?xml version=\'1.0\' encoding=\'UTF-8\'?>\n<config-auth client="vpn" type="init" aggregate-auth-version="2">\n  <version who="vpn">4.7.00136</version>\n  <device-id>linux-64</device-id>\n  <group-select>CI-VPN</group-select>\n  <group-access>https://vpn.company.com/</group-access>\n  <capabilities>\n    <auth-method>single-sign-on-v2</auth-method>\n  </capabilities>\n</config-auth>\n'
Starting new HTTPS connection (1): vpn.company.com:443
https://vpn.company.com:443 "POST / HTTP/1.1" 302 0
Resetting dropped connection: vpn.company.com
https://vpn.company.com:443 "GET /+webvpn+/index.html HTTP/1.1" 200 None
[debug    ] Auth init response received    [openconnect_sso.authenticator] content=b'<?xml version="1.0" encoding="UTF-8"?>\n\n<auth id="main">\n<title>SSL VPN Service</title>\n<ca status="disabled" href="/+CSCOCA+/login.html" />\n\n\n\n<banner></banner>\n<message>Please enter your username and password.</message>\n\n\n<form method="post" action="/+webvpn+/index.html">\n\n<input type="text" name="username" label="Username:" />\n<input type="password" name="password" label="Password:" />\n\n\n<select name="group_list" label="GROUP:">\n<option value="euwe-azuread" noaaa="0" >CI-VPN</option></select>\n\n<input type="submit" name="Login" value="Login" />\n<input type="reset" name="Clear" value="Clear" />\n\n\n</form>\n</auth>\n\n'
[error    ] Could not start authentication. Invalid response type in current state [openconnect_sso.authenticator] response=None
Traceback (most recent call last):
  File "/nix/store/gqrmbzqdcrd4brm20m6sydkpjc228d5f-openconnect-sso-0.5.0a1/bin/.openconnect-sso-wrapped", line 11, in <module>
    sys.exit(main())
  File "/nix/store/gqrmbzqdcrd4brm20m6sydkpjc228d5f-openconnect-sso-0.5.0a1/lib/python3.7/site-packages/openconnect_sso/cli.py", line 161, in main
    return app.run(args)
  File "/nix/store/gqrmbzqdcrd4brm20m6sydkpjc228d5f-openconnect-sso-0.5.0a1/lib/python3.7/site-packages/openconnect_sso/app.py", line 28, in run
    return asyncio.get_event_loop().run_until_complete(_run(args))
  File "/nix/store/k5rdcbcwwpvj7l9f1yvd5mfggcfz16kk-python3-3.7.5/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "/nix/store/gqrmbzqdcrd4brm20m6sydkpjc228d5f-openconnect-sso-0.5.0a1/lib/python3.7/site-packages/openconnect_sso/app.py", line 100, in _run
    auth_response = await authenticate_to(selected_profile, credentials, display_mode)
  File "/nix/store/gqrmbzqdcrd4brm20m6sydkpjc228d5f-openconnect-sso-0.5.0a1/lib/python3.7/site-packages/openconnect_sso/authenticator.py", line 27, in authenticate
    raise AuthenticationError(response)
openconnect_sso.authenticator.AuthenticationError: None
`

**Comment by jjeziorny** [comment]
On a side note, a colleague managed to connect to our VPN using this version, not sure why mine fails.
I've tried with the anyconnect client now and it works, so guess I'll stick to that.

**Comment by vlaci** [comment]
It could be some issue with the server address used. You can compare your logs with your colleague and see where it starts to differ.

**Comment by vlaci** [comment]
Feel free to reopen if your issue is still not resolved.
