### ISSUE TITLE
Traceback during first launch

### ISSUE THREAD

**Issue by dpoves** [vlaci/openconnect-sso#133]
Hello,

Thank you for developing this.

I have followed the installation instructions, but I get a traceback when launching the command. I have tried to find out what the possible trigger is but without much luck.

Is there anything missing or that I should be paying attention to?

$ openconnect-sso --version
Traceback (most recent call last):
  File "/home/user/.local/bin/openconnect-sso", line 5, in <module>
    from openconnect_sso.cli import main
  File "/home/user/.local/lib/python3.10/site-packages/openconnect_sso/cli.py", line 10, in <module>
    from openconnect_sso import app, config, __version__
  File "/home/user/.local/lib/python3.10/site-packages/openconnect_sso/app.py", line 16, in <module>
    from openconnect_sso.authenticator import Authenticator, AuthResponseError
  File "/home/user/.local/lib/python3.10/site-packages/openconnect_sso/authenticator.py", line 6, in <module>
    from openconnect_sso.saml_authenticator import authenticate_in_browser
  File "/home/user/.local/lib/python3.10/site-packages/openconnect_sso/saml_authenticator.py", line 3, in <module>
    from openconnect_sso.browser import Browser
  File "/home/user/.local/lib/python3.10/site-packages/openconnect_sso/browser/__init__.py", line 1, in <module>
    from .browser import Browser, DisplayMode, Terminated
  File "/home/user/.local/lib/python3.10/site-packages/openconnect_sso/browser/browser.py", line 5, in <module>
    from . import webengine_process as web
  File "/home/user/.local/lib/python3.10/site-packages/openconnect_sso/browser/webengine_process.py", line 14, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEngineView, QWebEngineScript, QWebEngineProfile
ImportError: /home/user/.local/lib/python3.10/site-packages/PyQt5/Qt5/lib/libQt5WebEngineCore.so.5: undefined symbol: _ZNSt12out_of_rangeC1EPKc, version Qt_5

**Comment by dpoves** [comment]
I managed to find out that there was a missing dependency.

Fixed it by installing

python3-pyqt5.qtwebengine
