### ISSUE TITLE
undefined symbol: _ZN14QReadWriteLock16destroyRecursiveEP21QReadWriteLockPrivate, version Qt_6_PRIVATE_API

### ISSUE THREAD

**Issue by eserte** [vlaci/openconnect-sso#154]
On an Ubuntu 20.04 system, with openconnect-sso 0.8.1:
```
$ openconnect-sso --authgroup ... -s https://...
Traceback (most recent call last):
  File "/usr/local/bin/openconnect-sso", line 5, in <module>
    from openconnect_sso.cli import main
  File "/home/.../.local/pipx/venvs/openconnect-sso/lib/python3.8/site-packages/openconnect_sso/cli.py", line 10, in <module>
    from openconnect_sso import app, config, __version__
  File "/home/.../.local/pipx/venvs/openconnect-sso/lib/python3.8/site-packages/openconnect_sso/app.py", line 17, in <module>
    from openconnect_sso.authenticator import Authenticator, AuthResponseError
  File "/home/.../.local/pipx/venvs/openconnect-sso/lib/python3.8/site-packages/openconnect_sso/authenticator.py", line 6, in <module>
    from openconnect_sso.saml_authenticator import authenticate_in_browser
  File "/home/.../.local/pipx/venvs/openconnect-sso/lib/python3.8/site-packages/openconnect_sso/saml_authenticator.py", line 3, in <module>
    from openconnect_sso.browser import Browser
  File "/home/.../.local/pipx/venvs/openconnect-sso/lib/python3.8/site-packages/openconnect_sso/browser/__init__.py", line 1, in <module>
    from .browser import Browser, DisplayMode, Terminated
  File "/home/.../.local/pipx/venvs/openconnect-sso/lib/python3.8/site-packages/openconnect_sso/browser/browser.py", line 5, in <module>
    from . import webengine_process as web
  File "/home/.../.local/pipx/venvs/openconnect-sso/lib/python3.8/site-packages/openconnect_sso/browser/webengine_process.py", line 12, in <module>
    from PyQt6.QtCore import QUrl, QTimer, pyqtSlot, Qt
ImportError: /home/.../.local/pipx/venvs/openconnect-sso/lib/python3.8/site-packages/PyQt6/QtCore.abi3.so: undefined symbol: _ZN14QReadWriteLock16destroyRecursiveEP21QReadWriteLockPrivate, version Qt_6_PRIVATE_API
```

0.7.3 worked fine on the same system (using a `full` install).

**Comment by stevie-** [comment]
Problem with PyQt6 and it's dependencys. Try again with latest versions
