### ISSUE TITLE
pipx installation fails

### ISSUE THREAD

**Issue by janskyview** [vlaci/openconnect-sso#158]
Hi, 

installations fails on command 

pipx install "openconnect-sso"
Fatal error from pip prevented installation. Full pip output in file:
    /home/gianmaria/.local/pipx/logs/cmd_2024-01-12_17.27.41_pip_errors.log

pip seemed to fail to build package:
    PyQt6<7.0.0,>=6.3.0

Some possibly relevant errors from pip install:
    error: subprocess-exited-with-error
    error: metadata-generation-failed

Error installing openconnect-sso.
------------------------------------------------------------------
Log's content: 

PIP STDOUT
----------
Collecting openconnect-sso
  Using cached openconnect_sso-0.8.1-py3-none-any.whl.metadata (7.4 kB)
Collecting PyQt6<7.0.0,>=6.3.0 (from openconnect-sso)
  Using cached PyQt6-6.6.1.tar.gz (1.0 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'error'

PIP STDERR
----------
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [31 lines of output]
      pyproject.toml: line 7: using '[tool.sip.metadata]' to specify the project metadata is deprecated and will be removed in SIP v7.0.0, use '[project]' instead
      Querying qmake about your Qt installation...
      Traceback (most recent call last):
        File "/home/gianmaria/.local/pipx/shared/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/gianmaria/.local/pipx/shared/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/gianmaria/.local/pipx/shared/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-vxr7b14j/overlay/lib/python3.11/site-packages/sipbuild/api.py", line 46, in build_wheel
          project = AbstractProject.bootstrap('wheel',
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-vxr7b14j/overlay/lib/python3.11/site-packages/sipbuild/abstract_project.py", line 87, in bootstrap
          project.setup(pyproject, tool, tool_description)
        File "/tmp/pip-build-env-vxr7b14j/overlay/lib/python3.11/site-packages/sipbuild/project.py", line 587, in setup
          self.apply_user_defaults(tool)
        File "/tmp/pip-install-5cszrz8n/pyqt6_429ebaedf5c5414990a6b57061df6afe/project.py", line 66, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/tmp/pip-build-env-vxr7b14j/overlay/lib/python3.11/site-packages/pyqtbuild/project.py", line 70, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/tmp/pip-build-env-vxr7b14j/overlay/lib/python3.11/site-packages/sipbuild/project.py", line 237, in apply_user_defaults
          self.builder.apply_user_defaults(tool)
        File "/tmp/pip-build-env-vxr7b14j/overlay/lib/python3.11/site-packages/pyqtbuild/builder.py", line 78, in apply_user_defaults
          self._get_qt_configuration()
        File "/tmp/pip-build-env-vxr7b14j/overlay/lib/python3.11/site-packages/pyqtbuild/builder.py", line 497, in _get_qt_configuration
          for line in project.read_command_pipe([self.qmake, '-query']):
        File "/tmp/pip-build-env-vxr7b14j/overlay/lib/python3.11/site-packages/sipbuild/project.py", line 554, in read_command_pipe
          raise UserException(
      sipbuild.exceptions.UserException
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
=============================================================================================

Is there a workaround for this? 
Thanks

**Comment by ataraxis** [comment]
@janskyview , did you find a workaround for this? I'm running into the same issue.

**Comment by janskyview** [comment]
@ataraxis , nope it's quite annoying because it's the only way (it seems) to get SAML Auth on a raspberry pi. 
It's probably an issue with pyqt6 related to packagin on kali which I'm on. 
I also got this answer which makes sense on a rpi forum: https://forums.raspberrypi.com/posting.php?mode=post&f=32
I haven't gone further than this.

**Comment by Vikasg7** [comment]
I am running into the same issue. Is there an alternative way to build this for Linux?

Thanks

**Comment by janskyview** [comment]
I'm looking for it but I can't seem to find any direction. 
It's so odd that Cisco Anyconnect is just for Windows on ARM and not Linux...

**Comment by Vikasg7** [comment]
@janskyview OK some success, We need to set AnyConnect User-agent while we set up our VPN in gnome and it will open a webkit window to authenticate, I can authenticate and connect to the VPN but my RDP connection is not working. 
https://wiki.archlinux.org/title/OpenConnect

**Comment by janskyview** [comment]
Did you use SAML Authentication? 
Because the only reason I'm not using openconnect is that it doesn't support that.

**Comment by Vikasg7** [comment]
@janskyview Not sure, but let's say my server is vpn.xxxxxx.com and the group is yyyyy, I hit connect, and integrated web view opens and I have to put in the login email and password and authenticate via open with something like Google authenticator and the browser will verify it and authenticate and close. Thats it. I think, it is called SAML and SSO, I guess.

**Comment by janskyview** [comment]
Thank you so much. Could you please show the command line you're using masking sensitive data?

**Comment by Vikasg7** [comment]
@janskyview I am not using any command line. I installed network-manager-openconnect and network-manager-openconnect-gnome, went to Gnome settings >> Network Tab >> Add a VPN Connection, select the VPN Type - Openconnect-Anyconnect, Use AnyConnect * User Agent, Hit Connect and go on from there. BTW VPN does connect but I am not able to RD to work. CISCO one work fine. I can only wait for Shitco to release the ARM64 binaries for linux.

**Comment by benpietras** [comment]
Hello,

Also having issues with openconnect-sso installation on an arm system (pi5, M1 mac with asahilinux).

strace indicates the install hits an infinite loop:
[0000ffff6b284da0] read(6, "Do you accept the terms of the l"..., 8192) = 4600

which fills up ram / swap, crashing the OS.

All good on x86_64.

Have tried pip, pipx, nix & make (compiling from source).

**Comment by GladOSkar** [comment]
I have the same issue now. Did anyone here find a solution?

**Comment by benpietras** [comment]
On asahi

    pipx install openconnect-sso

    sudo dnf install libwebp libwebp-devel libwebp-tools

(perhaps only first package needed)

as root:

    cd /usr/lib64

    ln -s  libwebp.so.6 libwebp.so

as user

    openconnect-sso --server=theserver --user=myuser

**Comment by GladOSkar** [comment]
I'm sorry, i was talking about the original issue where `pip` can't install `PyQt6`
