### ISSUE TITLE
Error when trying to connect

### ISSUE THREAD

**Issue by Ikizo** [vlaci/openconnect-sso#17]
Hello,

First of all thank you for the work on this script!

I unfortunately have an error while connecting... 
I have the "Sign in" window of microsoft which opens, I then have a redirection to the ADFS, the password and email address are automatically filled in, I click on "Sign In" than I must approve the "Sign in request" with my Microsoft Authenticator mobile phone. 
As soon as I approve the connection, the window closes with the following log:
```
[debug    ] Message received from browser  [openconnect_sso.browser.browser] message=SetCookie(name='webvpnlogin', value='1')
[debug    ] Waiting for message from browser process [openconnect_sso.browser.browser] 
[debug    ] Message received from browser  [openconnect_sso.browser.browser] message=SetCookie(name='acSamlv2Token', value='****************')
[debug    ] Waiting for message from browser process [openconnect_sso.browser.browser] 
[debug    ] Page loaded                    [webengine] url=https://vpn.domain.fr/+webvpn+/index.html
[debug    ] Message received from browser  [openconnect_sso.browser.browser] message=Url(url='https://vpn.domain.fr/+webvpn+/index.html')
[debug    ] Waiting for message from browser process [openconnect_sso.browser.browser] 
[debug    ] Browser loaded page            [openconnect_sso.saml_authenticator] url=https://vpn.domain.fr/+webvpn+/index.html
[debug    ] Page loaded                    [webengine] url=https://vpn.domain.fr/+CSCOE+/saml_ac_login.html
[debug    ] Message received from browser  [openconnect_sso.browser.browser] message=Url(url='https://vpn.domain.fr/+CSCOE+/saml_ac_login.html')
[debug    ] Waiting for message from browser process [openconnect_sso.browser.browser] 
[debug    ] Browser loaded page            [openconnect_sso.saml_authenticator] url=https://vpn.domain.fr/+CSCOE+/saml_ac_login.html
[info     ] Browser exited                 [openconnect_sso.browser.browser] 
https://vpn.domain.fr:443 "POST / HTTP/1.1" 200 None
[debug    ] Auth finish response received  [openconnect_sso.authenticator] content=b'<?xml version="1.0" encoding="UTF-8"?>\n<config-auth client="vpn" type="complete" aggregate-auth-version="2">\n<error id="9" param1="&#x0A;Your Anyconnect version is too old&#x0A;&#x0A;" param2="">Login denied.  %s</error>\n</config-auth>\n'
Traceback (most recent call last):
  File "/home/ikizo/.local/bin/openconnect-sso", line 8, in <module>
    sys.exit(main())
  File "/home/ikizo/.local/pipx/venvs/openconnect-sso/lib/python3.6/site-packages/openconnect_sso/cli.py", line 150, in main
    return app.run(args)
  File "/home/ikizo/.local/pipx/venvs/openconnect-sso/lib/python3.6/site-packages/openconnect_sso/app.py", line 28, in run
    return asyncio.get_event_loop().run_until_complete(_run(args))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/home/ikizo/.local/pipx/venvs/openconnect-sso/lib/python3.6/site-packages/openconnect_sso/app.py", line 98, in _run
    auth_response = await authenticate_to(selected_profile, credentials, display_mode)
  File "/home/ikizo/.local/pipx/venvs/openconnect-sso/lib/python3.6/site-packages/openconnect_sso/authenticator.py", line 43, in authenticate
    response = self._complete_authentication(auth_request_response, sso_token)
  File "/home/ikizo/.local/pipx/venvs/openconnect-sso/lib/python3.6/site-packages/openconnect_sso/authenticator.py", line 78, in _complete_authentication
    return parse_response(response)
  File "/home/ikizo/.local/pipx/venvs/openconnect-sso/lib/python3.6/site-packages/openconnect_sso/authenticator.py", line 138, in parse_response
    return parse_auth_complete_response(xml)
  File "/home/ikizo/.local/pipx/venvs/openconnect-sso/lib/python3.6/site-packages/openconnect_sso/authenticator.py", line 180, in parse_auth_complete_response
    assert xml.auth.get("id") == "success"
  File "src/lxml/objectify.pyx", line 231, in lxml.objectify.ObjectifiedElement.__getattr__
  File "src/lxml/objectify.pyx", line 450, in lxml.objectify._lookupChildOrRaise
AttributeError: no such child: auth
```

I use openconnect-sso 0.4.0 and openconnect v8.10 on Ubuntu 18.04
I see in the log that the xml tells me that I have a too old version of anyconnect, except that I'm using the latest version of openconnect, does that mean it's dead for me :) ?

Thank you

**Comment by vlaci** [comment]
The server says `Your Anyconnect version is too old`. I have just hardcoded an anyconnect version number that worked for me.
You can try adjusting the version number that gets sent in https://github.com/vlaci/openconnect-sso/blob/master/openconnect_sso/authenticator.py#L212 (and possibly other parts in this file)

If that solves your issue I can come up with a way to make the version number configurable.

**Comment by Ikizo** [comment]
Hello,

Thank you! It's working! 
The connection ends well by replacing only the version number on line 212.

Unfortunately, now the connection cuts off as soon as I make a network request but I have the same problem with the official Cisco client... I have a strange message of "CSTP Dead Peer Detection detected dead peer"...
But it's not from your script.

Thank you again.
