### ISSUE TITLE
cannot launch openconnect-sso on Ubuntu 24.04

### ISSUE THREAD

**Issue by damithsenanayake** [vlaci/openconnect-sso#172]
I just installed Ubuntu 24.04 LTS with Python 3.12. I do have installed PyQT6 and all required packages using pipx. However running ``` $ openconnect-sso``` results in the following error. 
```$ openconnect-sso
Traceback (most recent call last):
  File "/home/damith/.local/bin/openconnect-sso", line 5, in <module>
    from openconnect_sso.cli import main
  File "/home/damith/.local/lib/python3.12/site-packages/openconnect_sso/cli.py", line 10, in <module>
    from openconnect_sso import app, config, __version__
  File "/home/damith/.local/lib/python3.12/site-packages/openconnect_sso/app.py", line 17, in <module>
    from openconnect_sso.authenticator import Authenticator, AuthResponseError
  File "/home/damith/.local/lib/python3.12/site-packages/openconnect_sso/authenticator.py", line 6, in <module>
    from openconnect_sso.saml_authenticator import authenticate_in_browser
  File "/home/damith/.local/lib/python3.12/site-packages/openconnect_sso/saml_authenticator.py", line 3, in <module>
    from openconnect_sso.browser import Browser
  File "/home/damith/.local/lib/python3.12/site-packages/openconnect_sso/browser/__init__.py", line 1, in <module>
    from .browser import Browser, DisplayMode, Terminated
  File "/home/damith/.local/lib/python3.12/site-packages/openconnect_sso/browser/browser.py", line 5, in <module>
    from . import webengine_process as web
  File "/home/damith/.local/lib/python3.12/site-packages/openconnect_sso/browser/webengine_process.py", line 14, in <module>
    from PyQt6.QtWebEngineCore import QWebEngineScript, QWebEngineProfile, QWebEnginePage
ImportError: /home/damith/.local/lib/python3.12/site-packages/PyQt6/[QtGui.abi3.so](http://qtgui.abi3.so/): undefined symbol: _ZN5QFont11tagToStringEj, version Qt_6```

I am unable to get openconnect-sso running. I'm trying to use it with an anyconnect group with 2FA Azure auth.

**Comment by twwd** [comment]
I have the same issue with Fedora 40, KDE and QT 6.6.2.

**Comment by vacla** [comment]
@damithsenanayake @twwd You need to update QT, that will fix the issue

**Comment by twwd** [comment]
Fedora provides no newer version. 6.7 is not available (like in Arch). Must the QT version match the version of PyQT?

**Comment by vacla** [comment]
I got it from: https://pypi.org/project/PyQt6-Qt6/

**Comment by damithsenanayake** [comment]
I have the latest PyQT6 version (6.7.0) installed. The issue still persists. is there a way to launch the app while checking which pyqt version it's using?

**Comment by vacla** [comment]
There may been an update too of openconnect-sso , but not 100% sure

**Comment by damithsenanayake** [comment]
There were two installations of PyQt6 (user vs global). Uninstalling the older version fixed it. Thanks.
