### ISSUE TITLE
ModuleNotFoundError: No module named 'pip._vendor.six'

### ISSUE THREAD

**Issue by Blackbaud-JasonBodnar** [vlaci/openconnect-sso#27]
```
$ pipx install 'openconnect-sso[full]'
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/jbodnar/.local/pipx/venvs/openconnect-sso[full]/lib/python3.8/site-packages/pip/__main__.py", line 16, in <module>
    from pip._internal.cli.main import main as _main  # isort:skip # noqa
  File "/home/jbodnar/.local/pipx/venvs/openconnect-sso[full]/lib/python3.8/site-packages/pip/_internal/cli/main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/home/jbodnar/.local/pipx/venvs/openconnect-sso[full]/lib/python3.8/site-packages/pip/_internal/cli/autocompletion.py", line 9, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/home/jbodnar/.local/pipx/venvs/openconnect-sso[full]/lib/python3.8/site-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
    from pip._internal.cli import cmdoptions
  File "/home/jbodnar/.local/pipx/venvs/openconnect-sso[full]/lib/python3.8/site-packages/pip/_internal/cli/cmdoptions.py", line 24, in <module>
    from pip._internal.exceptions import CommandError
  File "/home/jbodnar/.local/pipx/venvs/openconnect-sso[full]/lib/python3.8/site-packages/pip/_internal/exceptions.py", line 10, in <module>
    from pip._vendor.six import iteritems
ModuleNotFoundError: No module named 'pip._vendor.six'
'/home/jbodnar/.local/pipx/venvs/openconnect-sso[full]/bin/python -m pip install --upgrade pip -q' failed

```

**Comment by Blackbaud-JasonBodnar** [comment]
This seems to be an issue with pipx installed by Debian:

https://github.com/pipxproject/pipx/issues/386
