### ISSUE TITLE
Invalid response type in current state [openconnect_sso.authenticator] response=None

### ISSUE THREAD

**Issue by ng0177** [vlaci/openconnect-sso#29]
I guess my company does not support `openconnect-sso` or do I miss something? Thanks!

```
$ openconnect-sso --server https://server.company.com/mfa --user user@company.com
Password (user@company.com): 
[info     ] Authenticating to VPN endpoint [openconnect_sso.app] address=https://server.company.com/mfa name=
[error    ] Could not start authentication. Invalid response type in current state [openconnect_sso.authenticator] response=None
Traceback (most recent call last):
  File "/usr/bin/openconnect-sso", line 33, in <module>
    sys.exit(load_entry_point('openconnect-sso==0.5.0', 'console_scripts', 'openconnect-sso')())
```

**Comment by vlaci** [comment]
You can check the debug logs (`-l debug` switch) to see what the response was from the server. It may shed some light on the issue you are having.

**Comment by vlaci** [comment]
Feel free to reopen if you'd like this issue to be further investigated.

**Comment by ng0177** [comment]
very kind! Will do.

**Comment by marcelopm** [comment]
During a reconnection, sometimes after waking from hibernation, I'm getting the same error.

```bash
$ openconnect-sso --server vpn.mycompany.com -l debug
Using selector: EpollSelector
[info     ] Authenticating to VPN endpoint [openconnect_sso.app] address=vpn.mycompany.com name=
Starting new HTTPS connection (1): vpn.mycompany.com:443
https://vpn.mycompany.com:443 "GET / HTTP/1.1" 200 92
[debug    ] Auth target url                [openconnect_sso.authenticator] url=https://vpn.mycompany.com/
[debug    ] Sending auth init request      [openconnect_sso.authenticator] content=b'<?xml version=\'1.0\' encoding=\'UTF-8\'?>\n<config-auth client="vpn" type="init" aggregate-auth-version="2">\n  <version who="vpn">4.7.00136</version>\n  <device-id>linux-64</device-id>\n  <group-select></group-select>\n  <group-access>https://vpn.mycompany.com/</group-access>\n  <capabilities>\n    <auth-method>single-sign-on-v2</auth-method>\n  </capabilities>\n</config-auth>\n'
Starting new HTTPS connection (1): vpn.mycompany.com:443
https://vpn.mycompany.com:443 "POST / HTTP/1.1" 302 0
Resetting dropped connection: vpn.mycompany.com
https://vpn.mycompany.com:443 "GET /+webvpn+/index.html HTTP/1.1" 200 None
[debug    ] Auth init response received    [openconnect_sso.authenticator] content=b'<?xml version="1.0" encoding="UTF-8"?>\n<!-- \n  Copyright (c) 2013, 2018-2019 by Cisco Systems, Inc.\n  All rights reserved.\n -->\n<auth id="main">\n<title>SSL VPN Service</title>\n<ca status="disabled" href="/+CSCOCA+/login.html" />\n\n\n\n<banner></banner>\n<message>Please enter your username and password.</message>\n\n\n<form method="post" action="/+webvpn+/index.html">\n\n<input type="text" name="username" label="Username:" />\n<input type="password" name="password" label="Password:" />\n\n\n<input type="hidden" name="tgroup" value="mycompany-VPN" />\n\n<input type="submit" name="Login" value="Login" />\n<input type="reset" name="Clear" value="Clear" />\n\n\n</form>\n</auth>\n\n'
[error    ] Could not start authentication. Invalid response type in current state [openconnect_sso.authenticator] response=None
Traceback (most recent call last):
  File "/home/myusername@mycompany.com/.local/bin/openconnect-sso", line 8, in <module>
    sys.exit(main())
  File "/home/myusername@mycompany.com/.local/pipx/venvs/openconnect-sso/lib/python3.8/site-packages/openconnect_sso/cli.py", line 169, in main
    return app.run(args)
  File "/home/myusername@mycompany.com/.local/pipx/venvs/openconnect-sso/lib/python3.8/site-packages/openconnect_sso/app.py", line 34, in run
    auth_response, selected_profile = asyncio.get_event_loop().run_until_complete(
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/myusername@mycompany.com/.local/pipx/venvs/openconnect-sso/lib/python3.8/site-packages/openconnect_sso/app.py", line 137, in _run
    auth_response = await authenticate_to(
  File "/home/myusername@mycompany.com/.local/pipx/venvs/openconnect-sso/lib/python3.8/site-packages/openconnect_sso/authenticator.py", line 28, in authenticate
    raise AuthenticationError(response)
openconnect_sso.authenticator.AuthenticationError: None
```

Restarting NetworkManager solves the issue for me:
```bash
sudo service network-manager restart
```
