### ISSUE TITLE
getpass.py error

### ISSUE THREAD

**Issue by mdbosworth** [vlaci/openconnect-sso#43]
I don't understand why this is an error...keyrings.alt-4.0.2 is installed, yet I don't get the login window.

Arch Linux - Zen-kernel - XPS 9570 i7

```
Warning: Password input may be echoed.
Password ($USER): Traceback (most recent call last):
  File "/usr/lib/python3.9/getpass.py", line 76, in unix_getpass
    termios.tcsetattr(fd, tcsetattr_flags, new)
termios.error: (5, 'Input/output error')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/getpass.py", line 79, in unix_getpass
    termios.tcsetattr(fd, tcsetattr_flags, old)
termios.error: (5, 'Input/output error')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/openconnect-sso", line 33, in <module>
    sys.exit(load_entry_point('openconnect-sso==0.6.2', 'console_scripts', 'openconnect-sso')())
  File "/usr/lib/python3.9/site-packages/openconnect_sso/cli.py", line 169, in main
    return app.run(args)
  File "/usr/lib/python3.9/site-packages/openconnect_sso/app.py", line 34, in run
    auth_response, selected_profile = asyncio.get_event_loop().run_until_complete(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/lib/python3.9/site-packages/openconnect_sso/app.py", line 111, in _run
    credentials.password = getpass.getpass(prompt=f"Password ({args.user}): ")
  File "/usr/lib/python3.9/getpass.py", line 91, in unix_getpass
    passwd = fallback_getpass(prompt, stream)
  File "/usr/lib/python3.9/getpass.py", line 126, in fallback_getpass
    return _raw_input(prompt, stream)
  File "/usr/lib/python3.9/getpass.py", line 148, in _raw_input
    raise EOFError
EOFError
```

**Comment by vlaci** [comment]
Do you invoke openconnect-sso from the terminal? Otherwise I have no idea what could be wrong.
