### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'password'

### ISSUE THREAD

**Issue by jwiechmann** [vlaci/openconnect-sso#50]
If I start the script (version 0.7.1) without the option -u to prevent the first "Initiating autologin" I got this error. The version 0.7.0 is working well.
```
openconnect-sso --server myServer
Traceback (most recent call last):
 File "/nix/store/pqzf8bpv74s309hlnv0iis09760f4107-python3.8-openconnect-sso-0.7.1/bin/.openconnect-sso-wrapped", line 9, in <module>
   sys.exit(main())
 File "/nix/store/pqzf8bpv74s309hlnv0iis09760f4107-python3.8-openconnect-sso-0.7.1/lib/python3.8/site-packages/openconnect_sso/cli.py", line 169, in main
   return app.run(args)
 File "/nix/store/pqzf8bpv74s309hlnv0iis09760f4107-python3.8-openconnect-sso-0.7.1/lib/python3.8/site-packages/openconnect_sso/app.py", line 34, in run
   auth_response, selected_profile = asyncio.get_event_loop().run_until_complete(
 File "/nix/store/v72cj06nk69cynckz2s12rhar25k1h7v-python3-3.8.5/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
   return future.result()
File "/nix/store/pqzf8bpv74s309hlnv0iis09760f4107-python3.8-openconnect-sso-0.7.1/lib/python3.8/site-packages/openconnect_sso/app.py", line 112, in _run
   if not credentials.password:
AttributeError: 'NoneType' object has no attribute 'password'
```

**Comment by vlaci** [comment]
Nice catch!
