### ISSUE TITLE
Ubuntu 22.04 issue

### ISSUE THREAD

**Issue by sakh251** [vlaci/openconnect-sso#88]
Hello,

I tried several installation steps on Ubuntu 22.04. All failed. 
Browser windows opens and after getting user/pass it shows you are now disconnected. This error appears in console:

[error    ] Could not finish authentication. Invalid response type in current state [openconnect_sso.authenticator] response=AuthRequestResponse(auth_id='main', auth_title='Login', auth_message='Please complete the authentication process in the AnyConnect Login window.', auth_error='Single sign-on AnyConnect token verification failure.', login_url='https://XXXX/+CSCOE+/saml/sp/login?tgname=fulltunnel&acsamlcap=v2', login_final_url='https://XXXX/+CSCOE+/saml_ac_login.html', token_cookie_name='acSamlv2Token', opaque=<Element opaque at 0x7fe31d16e240>)
Traceback (most recent call last):
  File "/home/salman/.local/bin/./openconnect-sso", line 8, in <module>
    sys.exit(main())
  File "/home/salman/.local/pipx/venvs/openconnect-sso/lib/python3.9/site-packages/openconnect_sso/cli.py", line 169, in main
    return app.run(args)
  File "/home/salman/.local/pipx/venvs/openconnect-sso/lib/python3.9/site-packages/openconnect_sso/app.py", line 34, in run
    auth_response, selected_profile = asyncio.get_event_loop().run_until_complete(
  File "/home/salman/anaconda3/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/salman/.local/pipx/venvs/openconnect-sso/lib/python3.9/site-packages/openconnect_sso/app.py", line 139, in _run
    auth_response = await authenticate_to(
  File "/home/salman/.local/pipx/venvs/openconnect-sso/lib/python3.9/site-packages/openconnect_sso/authenticator.py", line 50, in authenticate
    raise AuthenticationError(response)
openconnect_sso.authenticator.AuthenticationError: AuthRequestResponse(auth_id='main', auth_title='Login', auth_message='Please complete the authentication process in the AnyConnect Login window.', auth_error='Single sign-on AnyConnect token verification failure.', login_url='https://XXXX/+CSCOE+/saml/sp/login?tgname=fulltunnel&acsamlcap=v2', login_final_url='https://XXXX/+CSCOE+/saml_ac_login.html', token_cookie_name='acSamlv2Token', opaque=<Element opaque at 0x7fe31d16e240>)

**Comment by mvonkeil** [comment]
I'm experiencing the exact same issue for a couple of weeks now. Running Arch on 6.0.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 03 Nov 2022 18:01:58 +0000 x86_64 GNU/Linux

**Comment by ElectricRCAircraftGuy** [comment]
All installation attempts for me failed in Ubuntu 18.04 too. 

@sakh251 and @mvonkeil , can you please try my installation instructions here to see if they work for you? [How to use "openconnect" (via the `openconnect-sso` wrapper) with SAML and Duo two-factor authentication via Okta Single-Sign-on (SSO)](https://superuser.com/a/1753172/425838)
