### ISSUE TITLE
lxml.etree.XMLSyntaxError - unable to parse authentication response

### ISSUE THREAD

**Issue by mrbruins** [vlaci/openconnect-sso#97]
I'm trying to login to my company's VPN but get the following error. All help appreciated. I can connect using the AnyConnect app, but that app is utter garbage, hence looking to use the open connect alternative.

❯ openconnect-sso --server emea.vpn.company.com/GROUP --user user@company.com -l debug
Using selector: KqueueSelector
Loading KWallet
Loading SecretService
Loading Windows
Loading chainer
Loading libsecret
Loading macOS
[info     ] Authenticating to VPN endpoint [openconnect_sso.app] address=emea.vpn.company.com/GROUP name=
Starting new HTTPS connection (1): emea.vpn.company.com:443
https://emea.vpn.company.com:443 "GET /GROUP HTTP/1.1" 302 0
Starting new HTTPS connection (1): far03.vpn.company.com:443
https://far03.vpn.company.com:443 "GET /GROUP HTTP/1.1" 302 0
Resetting dropped connection: far03.vpn.company.com
https://far03.vpn.company.com:443 "GET /+CSCOE+/message.html?mc=2 HTTP/1.1" 200 None
[debug    ] Auth target url                [openconnect_sso.authenticator] url=https://far03.vpn.company.com/+CSCOE+/message.html
[debug    ] Sending auth init request      [openconnect_sso.authenticator] content=b'<?xml version=\'1.0\' encoding=\'UTF-8\'?>\n<config-auth client="vpn" type="init" aggregate-auth-version="2">\n  <version who="vpn">4.7.00136</version>\n  <device-id>linux-64</device-id>\n  <group-select></group-select>\n  <group-access>https://far03.vpn.company.com/+CSCOE+/message.html</group-access>\n  <capabilities>\n    <auth-method>single-sign-on-v2</auth-method>\n  </capabilities>\n</config-auth>\n'
Starting new HTTPS connection (1): far03.vpn.company.com:443
https://far03.vpn.company.com:443 "POST /+CSCOE+/message.html HTTP/1.1" 200 None
[debug    ] Auth init response received    [openconnect_sso.authenticator] content=b'\n<html>\n<body>\n<br>\n\n<center><b></b></center>\n</body>\n</html>\n\n\n'
Traceback (most recent call last):
  File "/Users/user/.local/bin/openconnect-sso", line 8, in <module>
    sys.exit(main())
  File "/Users/user/.local/pipx/venvs/openconnect-sso/lib/python3.10/site-packages/openconnect_sso/cli.py", line 169, in main
    return app.run(args)
  File "/Users/user/.local/pipx/venvs/openconnect-sso/lib/python3.10/site-packages/openconnect_sso/app.py", line 34, in run
    auth_response, selected_profile = asyncio.get_event_loop().run_until_complete(
  File "/Users/user/.pyenv/versions/3.10.6/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/Users/user/.local/pipx/venvs/openconnect-sso/lib/python3.10/site-packages/openconnect_sso/app.py", line 139, in _run
    auth_response = await authenticate_to(
  File "/Users/user/.local/pipx/venvs/openconnect-sso/lib/python3.10/site-packages/openconnect_sso/authenticator.py", line 22, in authenticate
    response = self._start_authentication()
  File "/Users/user/.local/pipx/venvs/openconnect-sso/lib/python3.10/site-packages/openconnect_sso/authenticator.py", line 67, in _start_authentication
    return parse_response(response)
  File "/Users/user/.local/pipx/venvs/openconnect-sso/lib/python3.10/site-packages/openconnect_sso/authenticator.py", line 137, in parse_response
    xml = objectify.fromstring(resp.content)
  File "src/lxml/objectify.pyx", line 2010, in lxml.objectify.fromstring
  File "src/lxml/etree.pyx", line 3254, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1913, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1800, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1141, in lxml.etree._BaseParser._parseDoc
  File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 654, in lxml.etree._raiseParseError
  File "<string>", line 7
lxml.etree.XMLSyntaxError: Opening and ending tag mismatch: br line 4 and body, line 7, column 9

**Comment by Amunhateb** [comment]
I am having the same issues:

`Traceback (most recent call last):
  File "/home/sergei/.local/bin/openconnect-sso", line 8, in <module>
    sys.exit(main())
  File "/home/sergei/.local/pipx/venvs/openconnect-sso/lib/python3.10/site-packages/openconnect_sso/cli.py", line 169, in main
    return app.run(args)
  File "/home/sergei/.local/pipx/venvs/openconnect-sso/lib/python3.10/site-packages/openconnect_sso/app.py", line 34, in run
    auth_response, selected_profile = asyncio.get_event_loop().run_until_complete(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/sergei/.local/pipx/venvs/openconnect-sso/lib/python3.10/site-packages/openconnect_sso/app.py", line 139, in _run
    auth_response = await authenticate_to(
  File "/home/sergei/.local/pipx/venvs/openconnect-sso/lib/python3.10/site-packages/openconnect_sso/authenticator.py", line 22, in authenticate
    response = self._start_authentication()
  File "/home/sergei/.local/pipx/venvs/openconnect-sso/lib/python3.10/site-packages/openconnect_sso/authenticator.py", line 67, in _start_authentication
    return parse_response(response)
  File "/home/sergei/.local/pipx/venvs/openconnect-sso/lib/python3.10/site-packages/openconnect_sso/authenticator.py", line 137, in parse_response
    xml = objectify.fromstring(resp.content)
  File "src/lxml/objectify.pyx", line 2010, in lxml.objectify.fromstring
  File "src/lxml/etree.pyx", line 3254, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1913, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1800, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1141, in lxml.etree._BaseParser._parseDoc
  File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 654, in lxml.etree._raiseParseError
  File "<string>", line 7
lxml.etree.XMLSyntaxError: Opening and ending tag mismatch: br line 4 and body, line 7, column 8`

**Comment by Amunhateb** [comment]
okay I've found the issue. My server has different usergroups defined and by default I was going to the wrong one. Just specify usergroup with "--usergroup GROUP_NAME"

**Comment by cengique** [comment]
It still doesn't work for me when I specify the group as `--server url/GROUP` on the command line. 

Using `--usergroup`, `-g`, or `--authgroup` removes the error, but I still can't effectively change the group. 

When I change the `user_group` in the TOML file, I go back to getting the same error posted above.
